apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mvaled-platform-dev

resources:
- ../../base

images:
- name: aegis-service
  newName: TODO
  newTag: TODO

patches:
- path: patch-deployment.yaml

configMapGenerator:
- behavior: replace
  envs:
  - config.env
  name: aegis-service-config
