---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aegis-local

resources:
  - ../../base

patches:
  - path: patch-deployment.yaml

# Non-sensitive config
configMapGenerator:
  - behavior: replace
    envs:
      - config.env
    name: aegis-service-config

# Secrets — locally we just use secretGenerator since
# there's no AWS Secrets Manager or ESO in Kind
secretGenerator:
  - envs:
      - secrets.env
    name: aegis-service-secrets
